apiVersion: v1
kind: Secret
metadata:
  name: authdata
  namespace: apps-was
type: Opaque
stringData:
  authdata.props: |-
    #
    # Configuration properties file for cells/DefaultCell01|security.xml#JAASAuthData_1597094577206#
    # Extracted on Tue Aug 11 15:30:36 UTC 2020
    #
    
    #
    # Section 1.0 ## Cell=!{cellName}:Security=:JAASAuthData=alias#DBUser
    #
    
    #
    # SubSection 1.0.0 # JAASAuthData Section
    #
    ResourceType=JAASAuthData
    ImplementingResourceType=GenericType
    ResourceId=Cell=!{cellName}:Security=:JAASAuthData=alias#DBUser
    AttributeInfo=authDataEntries
    #
    
    #
    #Properties
    #
    password="{xor}Oz1tNjEsK24=" #required
    alias=DBUser #required
    userId=db2inst1 #required
    description=
    
    #
    # End of Section 1.0# Cell=!{cellName}:Security=:JAASAuthData=alias#DBUser
    #
    #
    #
    EnvironmentVariablesSection
    #
    #
    #Environment Variables
    cellName=DefaultCell01
